config/routes.rb
Rails.application.routes.draw do

  root 'posts#homepage'

  resources :sessions, only:[:new, :create, :destroy]

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resource :users
  resources :posts

  resources :users, shallow: true do
    resources :posts
  end



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    validates :sport, presence: true
    validates :description, presence: true
    validates :address, presence: true
    geocoded_by :address
    after_validation :geocode
    validate :date_cannot_be_in_the_past
    # validate :time_cannot_be_in_the_past

    def date_cannot_be_in_the_past
        errors.add(:date, ' cannot be set for the past') if !date.blank? && date < Date.today
    end

    def time_cannot_be_in_the_past
        errors.add(:time, 'cannot be set for the past') if time.hour < Time.now.hour
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_secure_password
  validates :name,
    presence: true
  validates :email,
    uniqueness: true,
    presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  private
  def current_user
    User.where(id: session[:user_id]).first
  end
  helper_method :current_user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :new_post, only: [:index, :new]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @hash = Gmaps4rails.build_markers(@posts) do |post, marker|
      marker.lat post.latitude
      marker.lng post.longitude
    end
  end

  def homepage
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
    @posts = Post.all
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @posts = Post.all
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_url}
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def new_post
      @post = Post.new
    end
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:sport, :description,:date, :time, :address, :latitude, :longitude, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_email(params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to user_posts_path(@user), notice: "Welcome!"
      #will need this to redirect to the users posts
    else
      render :new, notice: "Account information not found!"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged Out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to root_url, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar" style="background-color:yellow;">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="/" class="navbar-brand" style="font-size:30px;">RecMe</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li>
                    <a style="font-size:22px;" data-target="#myModal" class="btn btn-lg" data-toggle="modal">Contact<span class="sr-only">(current)</span>
                    </a>
                </li>
                <li>
                    <a style="font-size:22px;" data-target="#aboutus" data-toggle="modal" class="btn btn-lg">About Us</a>
                </li>
                <li>
                    <a style="font-size:22px" href="/posts">All Postings</a>
                </li>
                <li>
                    <div id="user_header">
                        <% if current_user %>
                        <text style="font-size:20px;">Logged in as:</text>
                        &nbsp;
                        <text style="font-size:25px; color:#000033"><%= current_user.name %>
                            <span class="glyphicon glyphicon-user"></span>
                        </text>
                        &nbsp;
                        <text style="font-size:20px;">
                            <%= link_to "Log Out", logout_path %></text>
                    <% else %>
                        <text style="font-size:22px"><%= link_to "Sign Up", signup_path%></text>
                        <text style="font-size:20px">or</text>
                        <text style="font-size:22px"><%= link_to "Log In", login_path %></text>
                        <% end %>
                    </div>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
         <!--modals "contact us", "about us" -->
        <div id="myModal" class="modal fade">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title">Contact Us!</h4>
                    </div>
                    <div class="modal-body">
                        <div class="row">

                            <div class="col-md-6 text-center">

                                <%= image_tag('NigellKing.jpg',size:'170x300')%>
                                <h1>Nigell King</h1>

                                <a style="font-size:20px;" href="mailto:NigellKing@gmail.com">Email</a>
                                <a style="font-size:20px;"
                                    href="https://www.linkedin.com/in/nigell-king-36b92493?authType=NAME_SEARCH&authToken=W66E&locale=en_US&trk=tyah&trkInfo=clickedVertical%3Amynetwork%2CclickedEntityId%3A333732611%2CauthType%3ANAME_SEARCH%2Cidx%3A1-1-1%2CtarId%3A1481485379659%2Ctas%3Anigel">LinkedIn</a>
                                <a style="font-size:20px;" href="https://github.com/nking2010">GitHub</a>

                            </div>

                            <div class="col-md-6 text-center">
                                <%= image_tag('JohnArevalo.jpg',size:'170x300')%>
                                <h1>John Arevalo</h1>

                                <a style="font-size:20px;" href="mailto:John.Arevalo11@gmail.com">Email</a>
                                <a style="font-size:20px;"
                                    href="https://www.linkedin.com/in/john-arevalo-01743b129?authType=NAME_SEARCH&authToken=DpV4&locale=en_US&trk=tyah&trkInfo=clickedVertical%3Amynetwork%2CclickedEntityId%3A529595731%2CauthType%3ANAME_SEARCH%2Cidx%3A1-1-1%2CtarId%3A1481485443772%2Ctas%3AJohn%20A">LinkedIn</a>
                                <a style="font-size:20px;" href="https://github.com/Jarevalo92">GitHub</a>

                            </div>
                        </div>

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Thanks!</button>
                    </div>
                </div>
            </div>
        </div>
        <div id="aboutus" class="modal fade">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title">About us</h4>
                    </div>
                    <div class="modal-body">
                      <div class ="row">
                        <div class="col-md-12 text-center">
                          <nigell style="font-size:20px;">Nigell and John are junior developers based out of Fort Lauderdale, FL. They attended Wyncode Academy which include a Full Stack Development. HTML, CSS, JavaScript, Ruby, Ruby on Rails, and databases with SQL. Our curriculum also includes workflow management / version control, application deployment, and AGILE team dynamics.</nigell>
                        </div>
                      </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>

        <title>RecMe</title>
        <%= csrf_meta_tags %>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
      <%= render "layouts/navbar" %>
        <%= yield %>
    </body>
</html>

app/views/posts/_form.html.erb
<div class="container">
    <%= bootstrap_form_for(post,remote: true, label_errors: true, inline_errors: true) do |f| %>
    <% f.alert_message "Please fix the errors below!" %>
    <% if post.errors.any? %>

    <div id="error_explanation">
        <h2><%= pluralize(post.errors.count, "error") %>
            prohibited this post from being saved:</h2>

        <ul>
            <% post.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
        </ul>
    </div>
    <% end %>

    <div class="field">
        <%= f.select :sport, ["American Football","Basketball","Beach Volleyball", "Boxing","Canoe/Kayak", "Cycling","Diving","Equestrian","Fencing","Fútbol","Golf","Rugby", "Tennis", "Track and Field", "Triathlon","Weightlifting"], {label: "Which Sport are we playing?"} %>
    </div>

    <div class="field">
        <%= f.text_area :description, {label: "some useful information like age group, place, skill level"} %>
    </div>

    <div class="field">
        <%= f.text_field :address, {label:"address or name of location please so our computers can do some searching"}  %>
    </div>

    <div class="field">
        <%= f.date_select :date %>
    </div>

    <div class="field">
        <%= f.time_select :time, {ampm: true, minute_step: 15} %>
    </div>

    <div class="actions">
        <%= f.submit %>
        <%= link_to 'Back', posts_path, class:"btn btn-default"%>
    </div>
    <% end %>
</div>

app/views/posts/_posts.html.erb
<h1>Posts</h1>

<table class="table table-hover">
    <thead>
        <tr>
            <th>Sport</th>
            <th>Game Information</th>
            <th>Game Date</th>
            <th>Game Time</th>
            <th>Posted By</th>
            <th>Addresss</th>
            <!-- <th colspan="3"></th> -->
        </tr>
    </thead>

    <tbody>
      <% @posts.each do |post| %>

        <tr>
            <td><%= post.sport %></td>
            <td><%= post.description%></td>
            <td><%= post.date%></td>
            <td><%= post.time%></td>
            <td><%= post.user.name %></td>
            <td><%= post.address %></td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/homepage.html.erb
<!DOCTYPE HTML>
    <head>
        <style type="text/css">
            #hbl_code,
            #olark-data,
            .olark-key {
                display: none !important;
            }

            #runningman a:hover {
              background:none;
            }


        </style>
        <style type="text/css">
            @media print {
                #habla_beta_container_do_not_rely_on_div_classes_or_names {
                    /*display: none !important;*/
                }
            }

        </style>
    </head>
    <body style="background-color: #1B75BB;">
        <div class="container-fluid" id="header-section">
            <div class="row">
                <div class="container">
                    <div class="col-md-12">
                        <header>
                            <hgroup>
                                <h1 id="runningman">
                                    <%= link_to image_tag('runningman.png'), posts_path %>
                                </h1>

                            </h2>
                        </hgroup>
                    </header>
                </div>
            </div>
        </div>
        <div class="row">
            <div>
                <div class="col-md-12">
                    <section id="top-banner">
                        <div class="col-sm-3 col-sm-12 col-xs-8">
                            <div class="col-sm-3">
                                <div class="feature1">
                                    <img src="http://a.espncdn.com/photo/2014/0918/nfl_a_ChancellorThomas_sk_600.jpg" alt="Football" style="width:304px;height:228px;" style="PADDING-RIGHT: 5px"></img>

                                </div>
                            </div>
                            <div class="col-sm-3">
                                <div class="feature2">
                                    <img src="http://dailybruin.com/images/26842_web.sp.wvball.pica.jpg" alt="Volleyball" style="width:304px;height:228px;"></img>
                                </div>
                            </div>
                            <div class="col-sm-3">
                                <div class="feature4">
                                    <img src="http://www.collegescholarships.org/images/soccerscholarships.jpg" alt="Soccer" style="width:304px;height:228px;"></img>
                                </div>
                            </div>
                            <div class="col-sm-3">
                                <div class="feature4">
                                    <img src="http://freetaxusashootout.com/wp-content/uploads/2015/11/MJ.jpg" alt="Basketball" style="width:304px;height:228px;"></img>
                                </div>
                            </div>
                        </div>
                    </section>
                </div>
                <div id="why" class="col-lg-8 col-xs-12 col-s-8 col-md-6">
                    <section id="why-teampages">
                        <h4 style='font-size:50px'>Why should you choose RecMe?</h4>
                        <ul>

                            <li id="chris">

                                <p style='font-size:18px'>Social media app that allows a user to interact with other users and organizations while leaving real time descriptions!</p>
                            </li>

                            <li id="chris">

                                <p style='font-size:18px'></span>Save time and money on communication</p>
                        </li>
                        <li id="chris">

                            <p style='font-size:18px'>
                              It takes the users location, allows them to view the sports events around them, and sign up --- all from one place</p>
                        </li>
                        <li id="chris">


                            <p style='font-size:18px'>We welcome athletes of all ages! There is something for everyone!</p>
                        </li>
                    </ul>
                </section>
            </div>
            <div class="col-lg-4 col-xs-12 col-s-4 col-md-6">
                <h2 style="font-size:50px; color:yellow">Online Registration</h2>
                <p style="font-size:20px; color:yellow">Register online to your local sports center for games!</p>
                <a href="/signup" style="font-size:20px; color:White">Sign Up Today!</a>
            </div>
        </div>
    </div>
</div>

app/views/posts/index.html.erb
<!-- <script src="//maps.google.com/maps/api/js?key=AIzaSyATk7x0W5Fr3x3xyS6HGA47DWLIzZ0GbO8"></script> -->
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyATk7x0W5Fr3x3xyS6HGA47DWLIzZ0GbO8&libraries=places"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
<!-- only if you need custom infoboxes -->

<div class="container">
    <span>
        <h1>Posts</h1>
    </span>
    <div class="panel panel-warning">
        <table id="table" class="table table-hover">
            <div class="panel-heading">All Sports Listings!</div>
            <thead>
                <tr>
                    <th>Sport</th>
                    <th>Game Information</th>
                    <th>Game Date</th>
                    <th>Game Time</th>
                    <th>Posted By</th>
                    <th>Location</th>
                    <!-- <th colspan="3"></th> -->
                </tr>
            </thead>

            <tbody>
                <% @posts.each do |post| %>
                <tr>
                    <td><%= post.sport %></td>
                    <td><%= truncate(post.description, length: 100)%></td>
                    <td><%= post.date%></td>
                    <td><%= post.time.strftime"%I:%M %P" %></td>
                    <td><%= post.user.name %></td>
                    <td><%= post.address %></td>
                </tr>
                <% end %>
            </tbody>
        </table>
    </div>
    <%= render 'form', post: @post %>
    <div class="col-md-8 col-offset-2" id="map" style="width: 720px; height: 400px; float:center;"></div>

</div>



    <script type="text/javascript">
        handler = Gmaps.build('Google');
        handler.buildMap({
            provider: {},
            internal: {
                id: 'map'
            }
        }, function () {
            markers = handler.addMarkers(<%=raw @hash.to_json %>);
            handler.bounds.extendWith(markers);
            handler.fitMapToBounds();
        });
    </script>

app/views/posts/new.html.erb
<h1>New Game</h1>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyATk7x0W5Fr3x3xyS6HGA47DWLIzZ0GbO8&libraries=places"></script>

<%= render 'form', post: @post %>

<!-- <%# render 'posts',  %> -->

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sport:</strong>
  <%= @post.sport %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<p>
  <strong>Date:</strong>
  <%= @post.date %>
</p>

<p>
  <strong>Zip Code:</strong>
  <%= @post.address %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user.name %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/_form.html.erb
<%= bootstrap_form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="container-fluid">
  <div class="field">
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.email_field :email %>
  </div>

  <div class="field">
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Users</h1>

<table class=" table table-condensed table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', posts_path %>

app/views/users/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>